# Generated by Django 5.1.4 on 2024-12-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("resolved", "Resolved")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
