# Generated by Django 5.1.4 on 2024-12-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='issue',
            new_name='errormessage',
        ),
    ]
