# Generated by Django 5.1.4 on 2024-12-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0003_rename_issue_ticket_errormessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='errormessage',
            new_name='error',
        ),
    ]
